# Generated by Django 5.1.2 on 2026-05-19 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('binance_pay', 'Binance Pay'), ('bybit_pay', 'Bybit Pay'), ('cryptobot', 'CryptoBot'), ('usdt_bep20', 'USDT BEP-20'), ('usdt_trc20', 'USDT TRC-20'), ('ton', 'TON'), ('tron', 'TRON'), ('other', 'Other')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('proof_text', models.TextField(blank=True)),
                ('proof_file_id', models.CharField(blank=True, max_length=255)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payment_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='accounts.telegramuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
