# Generated by Django 5.1.15 on 2026-05-19 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='method',
            field=models.CharField(choices=[('binance_deposit', 'Binance Deposit'), ('binance_pay', 'Binance Pay'), ('bybit_pay', 'Bybit Pay'), ('cryptobot', 'CryptoBot'), ('usdt_bep20', 'USDT BEP-20'), ('usdt_trc20', 'USDT TRC-20'), ('ton', 'TON'), ('tron', 'TRON'), ('other', 'Other')], max_length=32),
        ),
        migrations.CreateModel(
            name='VerifiedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('binance', 'Binance')], default='binance', max_length=32)),
                ('txid', models.CharField(max_length=255, unique=True)),
                ('coin', models.CharField(max_length=20)),
                ('network', models.CharField(blank=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('raw_payload', models.JSONField(default=dict)),
                ('credited_at', models.DateTimeField(auto_now_add=True)),
                ('payment_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verified_deposit', to='payments.paymentrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verified_deposits', to='accounts.telegramuser')),
            ],
            options={
                'ordering': ['-credited_at'],
            },
        ),
    ]
