# Generated by Django 5.1.15 on 2026-05-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentrequest_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='payable_amount',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='requested_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
