# Generated by Django 5.1.15 on 2026-05-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentrequest_payable_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifieddeposit',
            name='provider',
            field=models.CharField(choices=[('binance', 'Binance'), ('bscscan', 'BscScan'), ('trongrid', 'TronGrid')], default='binance', max_length=32),
        ),
    ]
