# Generated by Django 5.1.15 on 2026-05-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_verifieddeposit_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifieddeposit',
            name='provider',
            field=models.CharField(choices=[('binance', 'Binance'), ('bscscan', 'BscScan'), ('moralis', 'Moralis'), ('trongrid', 'TronGrid')], default='binance', max_length=32),
        ),
    ]
