# Generated by Django 5.1.15 on 2026-05-28 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_database_indexes'),
        ('payments', '0007_add_binance_pay_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['expires_at'], name='payments_pa_expires_41fc25_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['user', 'status'], name='payments_pa_user_id_9f70d2_idx'),
        ),
    ]
