# Generated by Django 5.1.15 on 2026-05-21 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerapikey',
            name='can_create_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='developerapikey',
            name='daily_spend_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Set to 0 to disable the daily spend cap.', max_digits=12),
        ),
        migrations.AddField(
            model_name='developerapikey',
            name='max_order_quantity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='developerapikey',
            name='orders_per_minute',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='ApiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=80)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='api_access.developerapikey')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['api_key', 'endpoint', 'created_at'], name='api_access__api_key_30cabd_idx')],
            },
        ),
    ]
