# Generated by Django 5.1.15 on 2026-05-29 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_add_database_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('purchase', 'Purchase'), ('topup', 'Top-up'), ('support_ticket', 'Support Ticket'), ('api_call', 'API Call'), ('bot_command', 'Bot Command'), ('login', 'Login'), ('referral_signup', 'Referral Signup')], db_index=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.telegramuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_u_user_id_39836b_idx'), models.Index(fields=['activity_type', '-created_at'], name='analytics_u_activit_7e1dbf_idx')],
            },
        ),
    ]
