# Generated by Django 5.1.15 on 2026-05-19 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0003_paymentrequest_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='accounts.telegramuser'),
        ),
        migrations.CreateModel(
            name='ReferralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn'), ('reversed', 'Reversed')], db_index=True, default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_sources', to='accounts.telegramuser')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_earnings', to='accounts.telegramuser')),
                ('source_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_entries', to='payments.paymentrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
