# Generated by Django 5.1.15 on 2026-05-28 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_referralledger_admin_note_and_more'),
        ('payments', '0007_add_binance_pay_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='referralledger',
            index=models.Index(fields=['referrer', 'status'], name='accounts_re_referre_325fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['is_blocked'], name='accounts_te_is_bloc_150c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['notifications_enabled'], name='accounts_te_notific_ba480b_idx'),
        ),
    ]
