# Generated by Django 5.1.15 on 2026-05-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('action', models.CharField(max_length=80)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'action'], name='bot_botrate_user_id_94aa9b_idx')],
                'unique_together': {('user_id', 'action')},
            },
        ),
    ]
