# Generated by Django 5.1.15 on 2026-05-28 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_database_indexes'),
        ('orders', '0004_add_database_indexes'),
        ('payments', '0008_add_database_indexes'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['user', '-created_at'], name='wallet_wall_user_id_801842_idx'),
        ),
    ]
