# Generated by Django 5.1.15 on 2026-05-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_infinite_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='country_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='country_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='note_md',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('digital', 'Digital product'), ('telegram_account', 'Telegram account')], default='digital', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_note',
            field=models.TextField(blank=True),
        ),
    ]
