# Generated by Django 5.1.15 on 2026-05-30 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0001_initial'),
        ('catalog', '0002_product_allow_infinite_stock_product_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='active_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='active_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='has_orders',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='joined_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='joined_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='max_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='min_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='product_purchased',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_broadcasts', to='catalog.product'),
        ),
    ]
