# Generated by Django 5.1.15 on 2026-05-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0002_broadcast_active_after_broadcast_active_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='target_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ar', 'Arabic'), ('fr', 'French'), ('es', 'Spanish')], max_length=16),
        ),
    ]
