# Generated by Django 5.1.15 on 2026-05-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_allow_infinite_stock_product_country_code_and_more'),
        ('orders', '0002_order_delivered_payload_order_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_snapshot', models.TextField()),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('refunded', 'Refunded'), ('replaced', 'Replaced')], db_index=True, default='delivered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replaced_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('stock_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_item', to='catalog.stockitem')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
