# Generated by Django 5.1.15 on 2026-05-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_database_indexes'),
        ('catalog', '0002_product_allow_infinite_stock_product_country_code_and_more'),
        ('orders', '0003_orderitem'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
    ]
